/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes.index'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated/proposals.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes.new'
import { Route as AuthenticatedQuotesQuoteIdRouteImport } from './routes/_authenticated/quotes.$quoteId'
import { Route as AuthenticatedProposalsNewRouteImport } from './routes/_authenticated/proposals.new'
import { Route as AuthenticatedProposalsProposalIdRouteImport } from './routes/_authenticated/proposals.$proposalId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesQuoteIdRoute =
  AuthenticatedQuotesQuoteIdRouteImport.update({
    id: '/quotes/$quoteId',
    path: '/quotes/$quoteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsNewRoute =
  AuthenticatedProposalsNewRouteImport.update({
    id: '/proposals/new',
    path: '/proposals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsProposalIdRoute =
  AuthenticatedProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/_authenticated/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/_authenticated/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/_authenticated/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/trust'
    | '/billing'
    | '/chat'
    | '/clients'
    | '/dashboard'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/proposals/$proposalId'
    | '/proposals/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/chat/'
    | '/proposals/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/trust'
    | '/billing'
    | '/clients'
    | '/dashboard'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/proposals/$proposalId'
    | '/proposals/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/chat'
    | '/proposals'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/trust'
    | '/_authenticated/billing'
    | '/_authenticated/chat'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/proposals/$proposalId'
    | '/_authenticated/proposals/new'
    | '/_authenticated/quotes/$quoteId'
    | '/_authenticated/quotes/new'
    | '/_authenticated/chat/'
    | '/_authenticated/proposals/'
    | '/_authenticated/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/quotes/new': {
      id: '/_authenticated/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/$quoteId': {
      id: '/_authenticated/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/new': {
      id: '/_authenticated/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthenticatedProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$proposalId': {
      id: '/_authenticated/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof AuthenticatedProposalsProposalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProposalsProposalIdRoute: typeof AuthenticatedProposalsProposalIdRoute
  AuthenticatedProposalsNewRoute: typeof AuthenticatedProposalsNewRoute
  AuthenticatedQuotesQuoteIdRoute: typeof AuthenticatedQuotesQuoteIdRoute
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProposalsProposalIdRoute: AuthenticatedProposalsProposalIdRoute,
  AuthenticatedProposalsNewRoute: AuthenticatedProposalsNewRoute,
  AuthenticatedQuotesQuoteIdRoute: AuthenticatedQuotesQuoteIdRoute,
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
